### ISSUE TITLE
Https Request redirect to Http Request

### ISSUE THREAD

**Issue by nambh1999** [truonganhhoang/int3117-2019-2#3]
Em thử đăng nhập ở trên web https://hoclieu.vn qua cypress thì nó báo lỗi như này ạ 
"Mixed Content: The page at 'https://hoclieu.vn/__/#/tests/integration\test\sample.spec.js' was loaded over HTTPS, but requested an insecure resource 'http://accounts.sachmem.vn/users/sign_in'. This request has been blocked; the content must be served over HTTPS."
Em đọc trên cypress thì có thấy là nếu test bằng https mà chuyển về http thì nó sẽ báo lỗi ạ.

**Comment by truonganhhoang** [comment]
Em xem ở đây:
https://github.com/truonganhhoang/int3117-2019-2/issues/4

**Comment by duybn-0885** [comment]
Thêm `"chromeWebSecurity": false` trong `cypress.json`

**Comment by phamconganh** [comment]
@nambh1999 nếu bạn đã fix được lỗi thì mình đóng issue lại nhé
