### ISSUE TITLE
[Lỗi trang học liệu] Đã làm đúng hết nhưng kết quả bài lại bị sai

### ISSUE THREAD

**Issue by Lanhbao** [truonganhhoang/int3117-2019-2#50]
Đã làm đúng hết số câu trong bài kiểm tra, nhưng khi thoát ra xem kết quả thì lại không đúng hết tất cả

**Comment by tungdm97** [comment]
Thưa thầy em cũng bị vậy ạ. Ngoài ra có một số câu bị tự động bỏ qua nên lúc em xem lại kết quả mới thấy có những câu bị bỏ trống đáp án ạ

**Comment by truonganhhoang** [comment]
các em kiểm tra xem sai ở đâu để sửa code cho nó chạy đc với pm.
