### ISSUE TITLE
Hoclieu hiện lỗi " Rất tiếc! đã có lỗi xảy ra " và không thể load được bài tập 

### ISSUE THREAD

**Issue by chien9a11** [truonganhhoang/int3117-2019-2#51]
Thưa thầy , hiện tài em không thể vào được trang hoclieu dù kết nối mạng ổn định. Trang web hiện lỗi " Rất tiếc! đã có lỗi xảy ra " và không thể load tiếp được.

**Comment by vietnamican** [comment]
Mình cũng bị lỗi tương tự

**Comment by truonganhhoang** [comment]
https://github.com/truonganhhoang/int3117-2019-2/issues/54
