### ISSUE TITLE
Không thể vào trang hoclieu để làm bài tập

### ISSUE THREAD

**Issue by tungdm97** [truonganhhoang/int3117-2019-2#54]
Thưa thầy, hiện tại em và nhiều bạn khác đang gặp tình trạng không thể load được trang hoclieu để vào làm bài tập ạ

**Comment by truonganhhoang** [comment]
có lẽ hệ thống bị DOS, mình đã restart lại, các em vào lại thử xem, mình gia hạn đến 21:00 các bài tập hôm nay.
