### ISSUE TITLE
không di chuyển được giữa các câu

### ISSUE THREAD

**Issue by buihuynhduc** [truonganhhoang/int3117-2019-2#55]
từ bài 7 đi là khi di chuyển giữa các câu là không trở lại được các câu trước . do e có xem tất cả các câu rồi mới chọn câu dễ làm trước , nên khi di chuyển đến câu cuối cùng thì k thể trở về các câu trước được, e mong thầy có thể giúp để e có điều điện làm bài ạ  e cảm ơn thầy ạ

**Comment by vudung042** [comment]
Bạn đen quá, mình làm lúc nó lag nên là mất nhiều câu vl, đến lúc check lại nhiều câu chưa làm mà rõ ràng lúc làm đến kịch câu cuối cùng rồi :3

**Comment by buihuynhduc** [comment]
> Bạn đen quá, mình làm lúc nó lag nên là mất nhiều câu vl, đến lúc check lại nhiều câu chưa làm mà rõ ràng lúc làm đến kịch câu cuối cùng rồi :3

tại muốn xem từ hết đề rồi mới làm :(((

**Comment by truonganhhoang** [comment]
sẽ có thêm cảnh báo
