### ISSUE TITLE
Hỏi về lỗi "Cannot read property 'split' of underfined"

### ISSUE THREAD

**Issue by duong17020661** [truonganhhoang/int3117-2019-2#6]
Em test đến nút giao bài tập thì bị lỗi này sau khi click vào nút "Giao bài tập" trên test, trong khi click nút này trên web thì không lỗi.
Em cũng đã tìm hiểu nhưng chưa tìm được cách giải quyết. Mong thầy và các bạn có thể giúp. 
Em cảm ơn ạ.
![image](https://user-images.githubusercontent.com/43227742/66053260-34607780-e55c-11e9-88b6-a7e749108544.png)

**Comment by minhth1905** [comment]
Bạn share mình code được ko?

**Comment by duong17020661** [comment]
Code của mình đây bạn

![image](https://user-images.githubusercontent.com/43227742/66101677-e4c09100-e5d9-11e9-9bc4-445a85f0379e.png)

**Comment by minhth1905** [comment]
Coppy code ra cho mình trên http://codepad.org/ để mình check cho dễ nhé

**Comment by duong17020661** [comment]
Đây, bạn giúp mình với
http://codepad.org/NrWBLZS4
