### ISSUE TITLE
Lỗi không load được danh sách lớp học bằng cypress

### ISSUE THREAD

**Issue by nambh1999** [truonganhhoang/int3117-2019-2#7]
Em đã thêm đoạn code dưới đây vào cypress/support/index.js
Cypress.on('uncaught:exception', (err, runnable) => {
    debugger
    return false
})
Nhưng khi load đến danh sách lớp học: https://hoclieu.sachmem.vn/live_class/classes thì nó xuất hiện Uncaught exception như này ạ:
N {message: "adsbygoogle.push() error: No slot size for availab…on.cypress.io/uncaught-exception-from-application", name: "Uncaught TagError", pbr: true, stack: "TagError: adsbygoogle.push() error: No slot size f…syndication.com/pagead/js/adsbygoogle.js:1:28382)", onFail: ƒ}
![image](https://user-images.githubusercontent.com/55312288/66059242-e8b2cb80-e565-11e9-9262-aaf80e6f6011.png)

Do vậy nên trang danh sách lớp học không thể load được danh sách các lớp thôi ạ.
![Capture](https://user-images.githubusercontent.com/55312288/66059186-cc169380-e565-11e9-8896-4f856a3adbe1.PNG)

**Comment by minhth1905** [comment]
Bạn thêm vào file cypress/support/index.js dòng sau:
Cypress.on('uncaught:exception', (err, runnable) => { return false })

**Comment by nambh1999** [comment]
> 
> 
> Bạn thêm vào file cypress/support/index.js dòng sau:
> Cypress.on('uncaught:exception', (err, runnable) => { return false })

Em đã thêm vào rồi ạ nhưng nó vẫn bị như kia ạ

**Comment by minhth1905** [comment]
> > Bạn thêm vào file cypress/support/index.js dòng sau:
> > Cypress.on('uncaught:exception', (err, runnable) => { return false })
> 
> Em đã thêm vào rồi ạ nhưng nó vẫn bị như kia ạ

Bạn bỏ debugger xem.

**Comment by nambh1999** [comment]
> 
> 
> > > Bạn thêm vào file cypress/support/index.js dòng sau:
> > > Cypress.on('uncaught:exception', (err, runnable) => { return false })
> > 
> > 
> > Em đã thêm vào rồi ạ nhưng nó vẫn bị như kia ạ
> 
> Bạn bỏ debugger xem.

À sau khi bị như vậy mình thử bật debugger xem có lỗi nào khác không thôi nhưng mà kết quả vẫn như vậy

**Comment by tuanlinhtl17** [comment]
em cũng bị lỗi tương tự như vậy ạ, không thể load được danh sách lớp học

**Comment by tungtobi** [comment]
em cũng bị lỗi như trên ạ, vậy thì giờ xử lý sao ạ :(

**Comment by Maivu1611** [comment]
em cũng bị lỗi như trên ạ..

**Comment by duybn-0885** [comment]
mình có 1 cách như sau
+ các bạn đăng nhập sau đó lấy url của lớp học rồi visit lại, do nó là subdomain của trang ban đầu nên  sẽ không bị dính lỗi `2 domain` của cypress

**Comment by xyzrules** [comment]
nhóm em bị lỗi tương tự như trên, cùng với không thể load được UI và danh sách bài tập nên không kiểm tra được lọc bài tập.

**Comment by NguyenDung98** [comment]
Nhóm em cũng bị lỗi tương tự ạ

**Comment by hunglq-teko** [comment]
> > > Bạn thêm vào file cypress/support/index.js dòng sau:
> > > Cypress.on('uncaught:exception', (err, runnable) => { return false })
> > 
> > 
> > Em đã thêm vào rồi ạ nhưng nó vẫn bị như kia ạ
> 
> Bạn bỏ debugger xem.

tách ra làm các test, và ở test login nhớ set token cho cái phiên đăng nhập đó thì được anh ạ

**Comment by xyzrules** [comment]
> > > > Bạn thêm vào file cypress/support/index.js dòng sau:
> > > > Cypress.on('uncaught:exception', (err, runnable) => { return false })
> > > 
> > > 
> > > Em đã thêm vào rồi ạ nhưng nó vẫn bị như kia ạ
> > 
> > 
> > Bạn bỏ debugger xem.
> 
> tách ra làm các test, và ở test login nhớ set token cho cái phiên đăng nhập đó thì được anh ạ

Như thế nào à bạn?
