### ISSUE TITLE
Tài khoản đã bị đổi mật khẩu

### ISSUE THREAD

**Issue by doanthihoaithu** [truonganhhoang/int3117-2019-2#9]
Thưa thầy, trong quá trình test tối ngày 3/10/2019 thì tài khoản giáo viên không đăng nhập được do không đúng mật khẩu và đã bị khóa. Mong thầy kiểm tra lại để chúng em có quyền truy cập vào hệ thống.

**Comment by hunglq-teko** [comment]
Khi nào thầy kiểm tra xong thì cho bọn em thêm thời gian làm với ạ.

**Comment by nkimhung** [comment]
Nhóm em chức năng cũng cần có tài khoản giáo viên để vào test chức năng sửa
bài tập ạ

Vào Th 5, 3 thg 10, 2019 vào lúc 23:09 hunglq-teko <
notifications@github.com> đã viết:

**Comment by tungtobi** [comment]
Nhóm em cũng không login lại được nữa, tài khoản bị khóa ạ!

**Comment by honghoa1** [comment]
Thưa thầy, tài khoản hiện tại đã bị khóa, mong thầy gia hạn thêm thời gian để chúng em làm bài ạ

**Comment by minhth1905** [comment]
> Thưa thầy, tài khoản hiện tại đã bị khóa, mong thầy gia hạn thêm thời gian để chúng em làm bài ạ

cho mình thông tin tài khoản, mình mở khóa cho

**Comment by doanthihoaithu** [comment]
> > Thưa thầy, tài khoản hiện tại đã bị khóa, mong thầy gia hạn thêm thời gian để chúng em làm bài ạ
> 
> cho mình thông tin tài khoản, mình mở khóa cho

Tài khoản giaovien1@sachmem.vn

**Comment by minhth1905** [comment]
Tài khoản đã mở khóa nhé

**Comment by phamconganh** [comment]
@doanthihoaithu nếu không cò gì thì mình đóng issue lại nhé
